version: "3"
services:
     mosquitto:
        container_name: mosquitto
        restart: always
        build:
            context: ./mosquitto/build
            dockerfile: Dockerfile
        volumes:
            - ./mosquitto/etc:/mosquitto/config
            - ./mosquitto/var/data:/mosquitto/data
            - ./mosquitto/var/log:/mosquitto/log
        ports:
            - 1883:1883
#            - 8883:8883
#            - 9001:9001
#            - 9002:9002
        networks:
            - mosquitto-network

networks:
    mosquitto-network:
        driver: bridge
